### ISSUE TITLE
Missing dotenv module

### ISSUE THREAD

**Issue by Blinky-Keys** [RigidSeine/chat-less#3]
The `README` states that there needs to be a `.env` file created to store database secrets, but the file that uses them (`server/services/mongodb-create-ypl-client.jsx`) doesn't load the `dotenv` module to be able to read from the `.env` file:

```js
const {MongoClient, ServerApiVersion} = require('mongodb');

const createYapLessClient = () => {
    //Always URI encode the username and password using the 
    //encodeURIComponent method to ensure they are correctly parsed.
    const dbUsername = encodeURIComponent(process.env.MDB_USERNAME);
    const dbPassword = encodeURIComponent(process.env.MDB_PW);
    const clusterUrl =  process.env.MDB_CLUSTER_NAME;
    const authMechanism = "DEFAULT";

    const uri = `mongodb+srv://${dbUsername}:${dbPassword}@${clusterUrl}/?authMechanism=${authMechanism}`;

    return new MongoClient(uri, {
        serverApi: {
            version: ServerApiVersion.v1,
            strict: true,
            deprecationErrors: true,
        }
    });
};

module.exports = createYapLessClient;
```

**Comment by RigidSeine** [comment]
I don't know how to reproduce your issue since Node.js's `process` for using the environment variables doesn't require a `require` according to this [document](https://nodejs.org/en/learn/command-line/how-to-read-environment-variables-from-nodejs). This should just work locally on an appropriate Node version.
